### ISSUE TITLE
Some CreateableInstances cannot be made with Instance.new

### ISSUE THREAD

**Issue by Validark** [roblox-ts/rbx-types#37]
GameSettings, ParabolaAdornment, LuaSettings, PhysicsSettings, Player cannot be instantiated by Instance.new. Could we remove them from showing up in the prompts for `new Instance("")`? It comes from CreatableInstances

**Comment by osyrisrblx** [comment]
Might need to make a blacklist for this in ClassGenerator.ts, the API dump seems to indicate these are creatable.

**Comment by Validark** [comment]
These probably **are** all instantiable if running in CoreScripts (except Player, with the recent update). The thing is that users writing in Roblox-TS cannot instantiate instances of these classes.
