### ISSUE TITLE
UserInputService TouchMoved/TouchStarted/TouchEnded first arguments is an InputObject rather than an instance

### ISSUE THREAD

**Issue by karikera** [roblox-ts/rbx-types#70]

**Comment by Validark** [comment]
The first argument for each of these functions is indeed an InputObject.

https://developer.roblox.com/api-reference/event/UserInputService/TouchMoved
https://developer.roblox.com/api-reference/event/UserInputService/TouchStarted
https://developer.roblox.com/api-reference/event/UserInputService/TouchEnded

**Comment by karikera** [comment]
oh.. sorry about my bad english :(
